version: 2
jobs:
  build:
    parallelism: 1
    docker:
    - image: cimg/ruby:3.3
    - image: redis:3.2
    steps:
    - checkout
    - run: sed -i "s/spec.add_dependency 'sidekiq', '>= 5.0.0'/spec.add_dependency 'sidekiq', '>= 5.0.0', '< 7.0.0'/" sidekiq-clutch.gemspec
    - run: gem install bundler
    - run: bundle install
    - run: bundle exec rspec
