version: 2
jobs:
  build:
    parallelism: 1
    docker:
    - image: cimg/ruby:3.3
    - image: redis:8.0-M03-alpine
    steps:
    - checkout
    - run: gem install bundler
    - run: bundle install
    - run: bundle exec rspec
